server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/inventory?replicaSet=rs0

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
    producer:
      properties:
        acks: all

app:
  topics:
    orders: orders.v1
    inventory: inventory.v1
